#%RAML 1.0 Trait


queryParameters: 
  search:
    description: Specify the search query to limit return records based on simple search criteria that supports multiple query parameters using 'AND' operator. use ':' to seperate name/value and '+' to add more query parameters. 
    type: string
    required: false
    example: firstName:John+lastName:Doe
